"""Add MensagemCandidato

Revision ID: 3eceff4591dc
Revises: 78407918c548
Create Date: 2026-03-10 16:33:02.868331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eceff4591dc'
down_revision = '78407918c548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensagens_candidatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eleitor_id', sa.Integer(), nullable=False),
    sa.Column('candidato_id', sa.Integer(), nullable=True),
    sa.Column('assunto', sa.String(length=150), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('criada_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidato_id'], ['eleitores.id'], ),
    sa.ForeignKeyConstraint(['eleitor_id'], ['eleitores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensagens_candidatos')
    # ### end Alembic commands ###
