"""auto

Revision ID: 78407918c548
Revises: 
Create Date: 2026-03-07 13:41:58.018461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78407918c548'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bairros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('zona_eleitoral', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=256), nullable=True),
    sa.Column('perfil', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('eleitores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf_criptografado', sa.Text(), nullable=True),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('titulo_numero', sa.String(length=20), nullable=True),
    sa.Column('titulo_zona', sa.String(length=10), nullable=True),
    sa.Column('titulo_secao', sa.String(length=10), nullable=True),
    sa.Column('bairro_id', sa.Integer(), nullable=True),
    sa.Column('zona_eleitoral', sa.String(length=20), nullable=True),
    sa.Column('secao_eleitoral', sa.String(length=10), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('classificacao', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('filiacao', sa.String(length=20), nullable=True),
    sa.Column('ponto_focal_id', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bairro_id'], ['bairros.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ponto_focal_id'], ['eleitores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eleitores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eleitores_bairro_id'), ['bairro_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eleitores_nome'), ['nome'], unique=False)

    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('local', sa.String(length=255), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('cor', sa.String(length=10), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('eleitor_id', sa.Integer(), nullable=True),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.Column('bairro_id', sa.Integer(), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bairro_id'], ['bairros.id'], ),
    sa.ForeignKeyConstraint(['eleitor_id'], ['eleitores.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('acoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_acoes_eleitor_id'), ['eleitor_id'], unique=False)

    op.create_table('comunicacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('assunto', sa.String(length=200), nullable=True),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('enviado_em', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('erro_msg', sa.Text(), nullable=True),
    sa.Column('eleitor_id', sa.Integer(), nullable=False),
    sa.Column('enviado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eleitor_id'], ['eleitores.id'], ),
    sa.ForeignKeyConstraint(['enviado_por_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evento_participantes',
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('eleitor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eleitor_id'], ['eleitores.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.PrimaryKeyConstraint('evento_id', 'eleitor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evento_participantes')
    op.drop_table('comunicacoes')
    with op.batch_alter_table('acoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acoes_eleitor_id'))

    op.drop_table('acoes')
    op.drop_table('eventos')
    with op.batch_alter_table('eleitores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eleitores_nome'))
        batch_op.drop_index(batch_op.f('ix_eleitores_bairro_id'))

    op.drop_table('eleitores')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('configuracoes')
    op.drop_table('bairros')
    # ### end Alembic commands ###
